# -*- coding: utf-8 -*-
"""conflictbyahad (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yr4d4rBre1bQvqKjcXKYJkFHFhVvOD2l
"""

# !pip install pint sentence-transformers scikit-learn transformers torch spacy nltk
# !python -m spacy download en_core_web_sm

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import pipeline
import numpy as np
import re
from dataclasses import dataclass
from typing import List, Tuple, Set, Optional, Dict
from enum import Enum
import spacy
from nltk.corpus import wordnet
import nltk
from pint import UnitRegistry

# Download required NLTK data
try:
    nltk.download('wordnet', quiet=True)
    nltk.download('omw-1.4', quiet=True)
except:
    pass

# ========== MASSIVE DOMAIN KNOWLEDGE BASE ==========

class DomainKnowledge:
    """Comprehensive domain-specific knowledge - 10+ domains with extensive vocabulary"""

    DOMAINS = {
        'ecommerce': {
            'synonyms': {
                # Shopping/Cart synonyms (EXTENSIVE)
                ('cart', 'basket', 'shopping_cart', 'shopping_basket', 'bag', 'shopping_bag', 'trolley', 'buggy'): 'cart_entity',
                ('item', 'product', 'goods', 'merchandise', 'article', 'commodity', 'ware', 'stock_item', 'sku'): 'product_entity',
                ('customer', 'user', 'shopper', 'buyer', 'purchaser', 'consumer', 'client', 'patron', 'end_user'): 'customer_entity',
                ('add', 'place', 'put', 'insert', 'include', 'append', 'drop', 'throw_in'): 'add_action',
                ('remove', 'delete', 'take_out', 'eliminate', 'discard', 'drop', 'clear', 'erase', 'extract'): 'remove_action',

                # Order/Purchase synonyms (EXTENSIVE)
                ('order', 'purchase', 'transaction', 'sale', 'buy', 'procurement', 'acquisition'): 'order_entity',
                ('checkout', 'payment', 'pay', 'purchase_complete', 'settle', 'complete_order', 'finalize'): 'checkout_action',
                ('ship', 'deliver', 'send', 'dispatch', 'forward', 'transport', 'mail', 'courier'): 'shipping_action',
                ('track', 'trace', 'follow', 'monitor', 'locate', 'find'): 'track_action',

                # Account synonyms (EXTENSIVE)
                ('account', 'profile', 'user_account', 'member_account', 'customer_profile', 'user_profile'): 'account_entity',
                ('login', 'sign_in', 'authenticate', 'log_in', 'access', 'enter', 'connect'): 'login_action',
                ('logout', 'sign_out', 'log_out', 'exit', 'disconnect', 'end_session'): 'logout_action',
                ('register', 'sign_up', 'create_account', 'enroll', 'subscribe', 'join', 'signup'): 'register_action',

                # Inventory synonyms (EXTENSIVE)
                ('stock', 'inventory', 'availability', 'supply', 'stockpile', 'reserve'): 'inventory_entity',
                ('warehouse', 'storage', 'depot', 'storehouse', 'repository', 'stockroom'): 'warehouse_entity',
                ('in_stock', 'available', 'in_inventory', 'on_hand', 'stocked'): 'available_state',
                ('out_of_stock', 'unavailable', 'sold_out', 'depleted', 'exhausted'): 'unavailable_state',

                # Payment synonyms (EXTENSIVE)
                ('payment', 'pay', 'transaction', 'settlement', 'remittance', 'disbursement'): 'payment_action',
                ('refund', 'return_payment', 'reimbursement', 'payback', 'repayment', 'rebate'): 'refund_entity',
                ('discount', 'coupon', 'promo_code', 'voucher', 'offer', 'deal', 'reduction', 'markdown', 'rebate'): 'discount_entity',
                ('price', 'cost', 'amount', 'fee', 'charge', 'rate', 'value', 'expense'): 'price_entity',

                # Review/Rating synonyms
                ('review', 'rating', 'feedback', 'comment', 'evaluation', 'assessment', 'critique'): 'review_entity',
                ('rate', 'score', 'grade', 'rank', 'evaluate'): 'rating_action',

                # Wishlist/Favorites
                ('wishlist', 'favorites', 'saved_items', 'bookmarks', 'saved_list', 'favourites'): 'wishlist_entity',
                ('save', 'bookmark', 'favorite', 'keep', 'store', 'save_for_later'): 'save_action',

                # Search/Browse
                ('search', 'find', 'lookup', 'query', 'seek', 'hunt'): 'search_action',
                ('browse', 'explore', 'navigate', 'look_through', 'peruse'): 'browse_action',
                ('filter', 'sort', 'arrange', 'organize', 'categorize'): 'filter_action',

                # Notification/Alert
                ('notification', 'alert', 'message', 'notice', 'reminder', 'update'): 'notification_entity',
                ('notify', 'alert', 'inform', 'remind', 'update'): 'notify_action',
            },

            'antonyms': {
                ('add', 'remove'): True,
                ('increase', 'decrease'): True,
                ('allow', 'deny'): True,
                ('enable', 'disable'): True,
                ('online', 'offline'): True,
                ('mandatory', 'optional'): True,
                ('public', 'private'): True,
                ('available', 'unavailable'): True,
                ('in_stock', 'out_of_stock'): True,
                ('login', 'logout'): True,
                ('connect', 'disconnect'): True,
                ('activate', 'deactivate'): True,
                ('show', 'hide'): True,
                ('open', 'close'): True,
            },

            'business_rules': {
                'pricing': {
                    'annual_discount_range': (0.10, 0.25),
                    'max_discount_percent': 80,
                },
                'refund_policies': {
                    'digital_products': 'no_refund',
                    'physical_products': 'refundable',
                },
            }
        },

        'healthcare': {
            'synonyms': {
                # Patient synonyms (EXTENSIVE)
                ('patient', 'individual', 'subject', 'case', 'person', 'client'): 'patient_entity',

                # Medical professional synonyms (EXTENSIVE)
                ('doctor', 'physician', 'practitioner', 'clinician', 'md', 'medical_doctor', 'attending'): 'doctor_entity',
                ('nurse', 'rn', 'caregiver', 'nursing_staff', 'lpn'): 'nurse_entity',
                ('specialist', 'consultant', 'expert'): 'specialist_entity',

                # Medical record synonyms (EXTENSIVE)
                ('record', 'chart', 'medical_record', 'patient_record', 'file', 'history', 'emr', 'ehr'): 'record_entity',
                ('prescription', 'medication_order', 'rx', 'scrip', 'script'): 'prescription_entity',
                ('diagnosis', 'assessment', 'evaluation', 'finding', 'determination'): 'diagnosis_entity',

                # Appointment synonyms (EXTENSIVE)
                ('appointment', 'visit', 'consultation', 'session', 'meeting', 'checkup', 'exam'): 'appointment_entity',
                ('schedule', 'book', 'arrange', 'set', 'reserve', 'plan'): 'schedule_action',
                ('cancel', 'abort', 'terminate', 'stop', 'end'): 'cancel_action',

                # Treatment synonyms (EXTENSIVE)
                ('treatment', 'therapy', 'care', 'intervention', 'procedure', 'remedy'): 'treatment_entity',
                ('medication', 'medicine', 'drug', 'pharmaceutical', 'remedy', 'prescription'): 'medication_entity',
                ('prescribe', 'order', 'recommend', 'direct'): 'prescribe_action',

                # Test/Lab synonyms (EXTENSIVE)
                ('test', 'lab', 'examination', 'screening', 'analysis', 'assay', 'workup'): 'test_entity',
                ('result', 'finding', 'outcome', 'report', 'data'): 'result_entity',

                # Billing synonyms
                ('bill', 'invoice', 'statement', 'charge', 'claim'): 'billing_entity',
                ('insurance', 'coverage', 'plan', 'policy', 'benefit'): 'insurance_entity',
            },

            'antonyms': {
                ('approve', 'reject'): True,
                ('prescribe', 'discontinue'): True,
                ('admit', 'discharge'): True,
                ('start', 'stop'): True,
                ('active', 'inactive'): True,
            }
        },

        'finance': {
            'synonyms': {
                # Transaction synonyms (EXTENSIVE)
                ('transaction', 'payment', 'transfer', 'operation', 'deal', 'exchange'): 'transaction_entity',

                # Account synonyms (EXTENSIVE)
                ('account', 'balance', 'funds', 'bank_account', 'deposit_account'): 'account_entity',
                ('checking', 'current_account', 'checking_account'): 'checking_entity',
                ('savings', 'savings_account', 'deposit_account'): 'savings_entity',

                # Transaction actions (EXTENSIVE)
                ('withdraw', 'debit', 'take_out', 'extract', 'draw', 'pull_out'): 'withdraw_action',
                ('deposit', 'credit', 'add_funds', 'put_in', 'contribute', 'fund'): 'deposit_action',
                ('transfer', 'move', 'send', 'wire', 'transmit', 'remit'): 'transfer_action',

                # Loan synonyms (EXTENSIVE)
                ('loan', 'credit', 'advance', 'lending', 'borrowing', 'mortgage'): 'loan_entity',
                ('borrow', 'take_loan', 'get_credit'): 'borrow_action',
                ('repay', 'pay_back', 'settle', 'clear', 'amortize'): 'repay_action',

                # Investment synonyms (EXTENSIVE)
                ('invest', 'invest_in', 'put_money', 'fund', 'finance'): 'invest_action',
                ('stock', 'share', 'equity', 'security'): 'stock_entity',
                ('bond', 'debenture', 'fixed_income'): 'bond_entity',
                ('portfolio', 'holdings', 'investments'): 'portfolio_entity',

                # Interest/Rate synonyms
                ('interest', 'rate', 'yield', 'return', 'earning'): 'interest_entity',
                ('fee', 'charge', 'cost', 'expense', 'levy'): 'fee_entity',

                # Card synonyms (EXTENSIVE)
                ('card', 'credit_card', 'debit_card', 'bank_card', 'payment_card'): 'card_entity',
                ('atm', 'automated_teller', 'cash_machine', 'cashpoint'): 'atm_entity',
            },

            'antonyms': {
                ('deposit', 'withdraw'): True,
                ('credit', 'debit'): True,
                ('borrow', 'lend'): True,
                ('buy', 'sell'): True,
                ('increase', 'decrease'): True,
                ('profit', 'loss'): True,
            }
        },

        'education': {
            'synonyms': {
                # Student synonyms (EXTENSIVE)
                ('student', 'learner', 'pupil', 'scholar', 'trainee', 'enrollee', 'attendee'): 'student_entity',

                # Teacher synonyms (EXTENSIVE)
                ('teacher', 'instructor', 'educator', 'professor', 'faculty', 'tutor', 'lecturer', 'mentor'): 'teacher_entity',

                # Course synonyms (EXTENSIVE)
                ('course', 'class', 'module', 'subject', 'unit', 'program', 'curriculum', 'lesson'): 'course_entity',
                ('enroll', 'register', 'sign_up', 'join', 'take'): 'enroll_action',
                ('drop', 'withdraw', 'unenroll', 'leave'): 'drop_action',

                # Assignment synonyms (EXTENSIVE)
                ('assignment', 'homework', 'task', 'exercise', 'project', 'work', 'activity'): 'assignment_entity',
                ('submit', 'turn_in', 'hand_in', 'upload', 'deliver'): 'submit_action',

                # Grade synonyms (EXTENSIVE)
                ('grade', 'mark', 'score', 'result', 'rating', 'evaluation', 'assessment'): 'grade_entity',
                ('pass', 'succeed', 'clear', 'complete'): 'pass_action',
                ('fail', 'flunk', 'not_pass'): 'fail_action',

                # Examination synonyms (EXTENSIVE)
                ('exam', 'test', 'quiz', 'assessment', 'evaluation', 'examination'): 'exam_entity',
                ('midterm', 'mid_semester', 'mid_term'): 'midterm_entity',
                ('final', 'final_exam', 'end_term'): 'final_entity',

                # Attendance synonyms
                ('attendance', 'presence', 'participation'): 'attendance_entity',
                ('absent', 'missing', 'away'): 'absent_state',
                ('present', 'attending', 'here'): 'present_state',
            },

            'antonyms': {
                ('pass', 'fail'): True,
                ('enroll', 'drop'): True,
                ('present', 'absent'): True,
                ('start', 'finish'): True,
            }
        },

        'hrms': {
            'synonyms': {
                # Employee synonyms (EXTENSIVE)
                ('employee', 'staff', 'worker', 'personnel', 'team_member', 'associate', 'member', 'hire'): 'employee_entity',

                # Salary synonyms (EXTENSIVE)
                ('salary', 'compensation', 'pay', 'wage', 'remuneration', 'earnings', 'income', 'paycheck'): 'salary_entity',
                ('bonus', 'incentive', 'reward', 'extra_pay', 'premium'): 'bonus_entity',

                # Leave synonyms (EXTENSIVE)
                ('leave', 'absence', 'time_off', 'vacation', 'holiday', 'pto', 'day_off'): 'leave_entity',
                ('sick_leave', 'medical_leave', 'illness_leave'): 'sick_leave_entity',
                ('annual_leave', 'vacation', 'holiday'): 'annual_leave_entity',
                ('apply', 'request', 'submit', 'file'): 'apply_action',
                ('approve', 'accept', 'authorize', 'grant', 'sanction'): 'approve_action',
                ('reject', 'deny', 'decline', 'refuse', 'disapprove'): 'reject_action',

                # Department synonyms (EXTENSIVE)
                ('department', 'division', 'team', 'unit', 'section', 'branch', 'group'): 'department_entity',
                ('manager', 'supervisor', 'head', 'lead', 'boss', 'director'): 'manager_entity',

                # Recruitment synonyms (EXTENSIVE)
                ('recruit', 'hire', 'employ', 'onboard', 'bring_on'): 'recruit_action',
                ('candidate', 'applicant', 'job_seeker', 'prospect'): 'candidate_entity',
                ('interview', 'meeting', 'discussion', 'screening'): 'interview_entity',

                # Performance synonyms (EXTENSIVE)
                ('performance', 'evaluation', 'review', 'appraisal', 'assessment', 'rating'): 'performance_entity',
                ('promote', 'advance', 'elevate', 'upgrade'): 'promote_action',
                ('terminate', 'fire', 'dismiss', 'let_go', 'remove'): 'terminate_action',
            },

            'antonyms': {
                ('hire', 'fire'): True,
                ('promote', 'demote'): True,
                ('approve', 'reject'): True,
                ('active', 'inactive'): True,
            }
        },

        'crm': {
            'synonyms': {
                # Lead synonyms (EXTENSIVE)
                ('lead', 'prospect', 'potential_customer', 'potential_client', 'opportunity'): 'lead_entity',
                ('contact', 'client', 'customer', 'account', 'relation'): 'contact_entity',

                # Deal synonyms (EXTENSIVE)
                ('deal', 'opportunity', 'sale', 'transaction', 'business'): 'deal_entity',
                ('pipeline', 'sales_funnel', 'workflow', 'process'): 'pipeline_entity',
                ('stage', 'phase', 'step', 'level'): 'stage_entity',

                # Actions (EXTENSIVE)
                ('qualify', 'validate', 'verify', 'confirm'): 'qualify_action',
                ('convert', 'close', 'win', 'finalize', 'complete'): 'convert_action',
                ('lose', 'fail', 'miss', 'forfeit'): 'lose_action',
                ('follow_up', 'followup', 'check_in', 'reach_out'): 'followup_action',

                # Campaign synonyms (EXTENSIVE)
                ('campaign', 'initiative', 'program', 'promotion', 'drive'): 'campaign_entity',
                ('email', 'message', 'correspondence', 'communication'): 'email_entity',
                ('call', 'phone', 'ring', 'dial'): 'call_entity',

                # Meeting synonyms
                ('meeting', 'appointment', 'session', 'discussion', 'conference'): 'meeting_entity',
                ('schedule', 'book', 'arrange', 'plan', 'set'): 'schedule_action',
            },

            'antonyms': {
                ('win', 'lose'): True,
                ('qualify', 'disqualify'): True,
                ('convert', 'lose'): True,
            }
        },

        'logistics': {
            'synonyms': {
                # Shipment synonyms (EXTENSIVE)
                ('shipment', 'delivery', 'package', 'parcel', 'consignment', 'cargo', 'freight'): 'shipment_entity',
                ('order', 'consignment', 'load', 'batch'): 'order_entity',

                # Location synonyms (EXTENSIVE)
                ('warehouse', 'depot', 'storage_facility', 'distribution_center', 'hub', 'facility'): 'warehouse_entity',
                ('address', 'location', 'destination', 'place'): 'address_entity',

                # Action synonyms (EXTENSIVE)
                ('ship', 'send', 'dispatch', 'forward', 'transport', 'deliver'): 'ship_action',
                ('track', 'monitor', 'trace', 'follow', 'locate'): 'track_action',
                ('receive', 'accept', 'get', 'collect', 'obtain'): 'receive_action',
                ('return', 'send_back', 'reverse', 'reship'): 'return_action',

                # Status synonyms (EXTENSIVE)
                ('in_transit', 'shipping', 'on_the_way', 'en_route'): 'transit_state',
                ('delivered', 'arrived', 'completed', 'received'): 'delivered_state',
                ('pending', 'waiting', 'queued', 'scheduled'): 'pending_state',

                # Vehicle synonyms
                ('vehicle', 'truck', 'van', 'transport', 'carrier'): 'vehicle_entity',
                ('driver', 'operator', 'courier', 'deliverer'): 'driver_entity',
            },

            'antonyms': {
                ('send', 'receive'): True,
                ('ship', 'return'): True,
                ('pickup', 'delivery'): True,
            }
        },

        'hotel': {
            'synonyms': {
                # Reservation synonyms (EXTENSIVE)
                ('reservation', 'booking', 'accommodation', 'appointment', 'arrangement'): 'reservation_entity',
                ('book', 'reserve', 'schedule', 'arrange', 'secure'): 'book_action',
                ('cancel', 'abort', 'terminate', 'void', 'withdraw'): 'cancel_action',

                # Guest synonyms (EXTENSIVE)
                ('guest', 'visitor', 'customer', 'client', 'patron', 'lodger'): 'guest_entity',

                # Room synonyms (EXTENSIVE)
                ('room', 'suite', 'accommodation', 'chamber', 'unit', 'lodging'): 'room_entity',
                ('single', 'single_room', 'single_occupancy'): 'single_entity',
                ('double', 'double_room', 'twin'): 'double_entity',
                ('suite', 'deluxe', 'premium_room'): 'suite_entity',

                # Actions (EXTENSIVE)
                ('check_in', 'checkin', 'arrival', 'registration', 'sign_in'): 'checkin_action',
                ('check_out', 'checkout', 'departure', 'leave', 'vacate'): 'checkout_action',

                # Service synonyms (EXTENSIVE)
                ('service', 'amenity', 'facility', 'feature', 'offering'): 'service_entity',
                ('housekeeping', 'cleaning', 'maintenance', 'upkeep'): 'housekeeping_entity',
                ('concierge', 'reception', 'front_desk', 'service_desk'): 'concierge_entity',
            },

            'antonyms': {
                ('check_in', 'check_out'): True,
                ('book', 'cancel'): True,
                ('available', 'occupied'): True,
            }
        },

        'telecom': {
            'synonyms': {
                # Subscriber synonyms (EXTENSIVE)
                ('subscriber', 'customer', 'user', 'client', 'account_holder'): 'subscriber_entity',

                # Plan synonyms (EXTENSIVE)
                ('plan', 'package', 'subscription', 'service', 'scheme', 'tariff'): 'plan_entity',
                ('prepaid', 'pay_as_you_go', 'payg'): 'prepaid_entity',
                ('postpaid', 'contract', 'billed'): 'postpaid_entity',

                # Actions (EXTENSIVE)
                ('recharge', 'top_up', 'refill', 'reload', 'add_credit'): 'recharge_action',
                ('activate', 'enable', 'turn_on', 'switch_on', 'start'): 'activate_action',
                ('deactivate', 'disable', 'turn_off', 'suspend', 'stop'): 'deactivate_action',

                # Services (EXTENSIVE)
                ('data', 'bandwidth', 'internet', 'mobile_data', 'data_plan'): 'data_entity',
                ('call', 'voice', 'voice_call', 'phone_call', 'calling'): 'call_entity',
                ('sms', 'text', 'message', 'text_message', 'messaging'): 'sms_entity',

                # Network synonyms
                ('network', 'coverage', 'signal', 'connectivity'): 'network_entity',
                ('roaming', 'international', 'overseas'): 'roaming_entity',
            },

            'antonyms': {
                ('activate', 'deactivate'): True,
                ('enable', 'disable'): True,
                ('prepaid', 'postpaid'): True,
            }
        },

        'insurance': {
            'synonyms': {
                # Policy synonyms (EXTENSIVE)
                ('policy', 'coverage', 'plan', 'insurance_plan', 'contract'): 'policy_entity',
                ('policyholder', 'insured', 'subscriber', 'member'): 'policyholder_entity',

                # Claim synonyms (EXTENSIVE)
                ('claim', 'request', 'submission', 'application', 'demand'): 'claim_entity',
                ('file', 'submit', 'lodge', 'make', 'raise'): 'file_action',
                ('process', 'review', 'evaluate', 'assess', 'examine'): 'process_action',
                ('approve', 'accept', 'authorize', 'sanction', 'grant'): 'approve_action',
                ('reject', 'deny', 'decline', 'refuse', 'dismiss'): 'reject_action',

                # Premium synonyms (EXTENSIVE)
                ('premium', 'payment', 'installment', 'contribution', 'fee'): 'premium_entity',
                ('pay', 'remit', 'settle', 'clear'): 'pay_action',

                # Beneficiary synonyms (EXTENSIVE)
                ('beneficiary', 'recipient', 'payee', 'heir', 'nominee'): 'beneficiary_entity',

                # Coverage synonyms (EXTENSIVE)
                ('coverage', 'protection', 'benefit', 'indemnity', 'compensation'): 'coverage_entity',
                ('deductible', 'excess', 'copay', 'out_of_pocket'): 'deductible_entity',
            },

            'antonyms': {
                ('approve', 'reject'): True,
                ('active', 'expired'): True,
                ('covered', 'excluded'): True,
            }
        },

        'banking': {
            'synonyms': {
                # Account types (EXTENSIVE)
                ('account', 'bank_account', 'profile', 'customer_account'): 'account_entity',
                ('savings', 'savings_account', 'deposit_account'): 'savings_entity',
                ('checking', 'current', 'checking_account', 'current_account'): 'checking_entity',

                # Transaction synonyms (EXTENSIVE)
                ('transaction', 'operation', 'activity', 'movement', 'entry'): 'transaction_entity',
                ('withdraw', 'withdrawal', 'debit', 'take_out'): 'withdraw_action',
                ('deposit', 'credit', 'add', 'put_in'): 'deposit_action',
                ('transfer', 'move', 'send', 'wire', 'remit'): 'transfer_action',

                # Balance synonyms
                ('balance', 'funds', 'amount', 'total', 'sum'): 'balance_entity',
                ('statement', 'report', 'summary', 'record'): 'statement_entity',

                # Card synonyms (EXTENSIVE)
                ('card', 'debit_card', 'credit_card', 'bank_card', 'atm_card'): 'card_entity',
                ('pin', 'password', 'code', 'passcode', 'secret_code'): 'pin_entity',

                # Branch/ATM synonyms
                ('branch', 'office', 'location', 'outlet'): 'branch_entity',
                ('atm', 'cash_machine', 'automated_teller', 'cashpoint'): 'atm_entity',
            },

            'antonyms': {
                ('deposit', 'withdraw'): True,
                ('credit', 'debit'): True,
                ('open', 'close'): True,
                ('activate', 'block'): True,
            }
        },

        'restaurant': {
            'synonyms': {
                # Order synonyms (EXTENSIVE)
                ('order', 'request', 'booking', 'reservation'): 'order_entity',
                ('place', 'make', 'submit', 'create'): 'place_action',

                # Menu synonyms (EXTENSIVE)
                ('menu', 'items', 'dishes', 'offerings', 'selection'): 'menu_entity',
                ('item', 'dish', 'meal', 'food', 'entree'): 'item_entity',

                # Customer synonyms (EXTENSIVE)
                ('customer', 'guest', 'patron', 'diner', 'visitor'): 'customer_entity',

                # Table synonyms (EXTENSIVE)
                ('table', 'seat', 'seating', 'spot', 'reservation'): 'table_entity',
                ('book', 'reserve', 'secure', 'arrange'): 'book_action',

                # Delivery synonyms (EXTENSIVE)
                ('delivery', 'takeout', 'pickup', 'carryout', 'to_go'): 'delivery_entity',
                ('deliver', 'bring', 'send', 'dispatch'): 'deliver_action',
            },

            'antonyms': {
                ('dine_in', 'takeout'): True,
                ('available', 'unavailable'): True,
            }
        },
    }

    # COMMON CONFLICT PATTERNS ACROSS ALL DOMAINS
    UNIVERSAL_CONFLICTS = {
        'negation_pairs': [
            ('must', 'must not'),
            ('should', 'should not'),
            ('can', 'cannot'),
            ('allow', 'deny'),
            ('enable', 'disable'),
            ('require', 'prohibit'),
            ('mandatory', 'forbidden'),
            ('always', 'never'),
            ('all', 'no'),
        ],

        'scope_conflicts': [
            ('all', 'some'),
            ('every', 'certain'),
            ('always', 'sometimes'),
            ('mandatory', 'optional'),
            ('required', 'optional'),
        ],

        'connectivity_conflicts': [
            ('online', 'offline'),
            ('connected', 'disconnected'),
            ('internet', 'no_internet'),
        ]
    }

    @classmethod
    def get_domain_synonyms(cls, domain: str) -> Dict:
        """Get synonym mappings for a specific domain"""
        return cls.DOMAINS.get(domain, {}).get('synonyms', {})

    @classmethod
    def get_domain_antonyms(cls, domain: str) -> Dict:
        """Get antonym pairs for a specific domain"""
        return cls.DOMAINS.get(domain, {}).get('antonyms', {})

    @classmethod
    def is_domain_synonym(cls, word1: str, word2: str, domain: str) -> bool:
        """Check if two words are synonyms in a specific domain"""
        synonyms = cls.get_domain_synonyms(domain)
        word1_lower = word1.lower().replace(' ', '_')
        word2_lower = word2.lower().replace(' ', '_')

        for syn_group, category in synonyms.items():
            if word1_lower in syn_group and word2_lower in syn_group:
                return True
        return False

    @classmethod
    def is_domain_antonym(cls, word1: str, word2: str, domain: str) -> bool:
        """Check if two words are antonyms in a specific domain"""
        antonyms = cls.get_domain_antonyms(domain)
        word1_lower = word1.lower().replace(' ', '_')
        word2_lower = word2.lower().replace(' ', '_')

        for pair, _ in antonyms.items():
            if (word1_lower in pair[0] and word2_lower in pair[1]) or \
               (word1_lower in pair[1] and word2_lower in pair[0]):
                return True
        return False

    @classmethod
    def detect_domain(cls, requirements: List[str]) -> str:
        """Auto-detect the most likely domain from requirements"""
        domain_scores = {domain: 0 for domain in cls.DOMAINS.keys()}

        combined_text = ' '.join(requirements).lower()

        for domain, domain_data in cls.DOMAINS.items():
            synonyms = domain_data.get('synonyms', {})
            for syn_group in synonyms.keys():
                for word in syn_group:
                    if word in combined_text:
                        domain_scores[domain] += 1

        best_domain = max(domain_scores, key=domain_scores.get)
        return best_domain if domain_scores[best_domain] > 0 else 'ecommerce'

# ========== ENUMS & DATA CLASSES ==========

class IssueType(Enum):
    DUPLICATE = "duplicate"
    CONFLICT = "conflict"
    INCONSISTENCY = "inconsistency"

@dataclass
class Detection:
    req1_id: int
    req2_id: int
    req1: str
    req2: str
    issue_type: IssueType
    confidence: float
    evidence: dict

# ========== ENHANCED NLP UTILITIES ==========

class DomainAwareNLPUtils:
    """Domain-aware NLP utilities with enhanced synonym detection"""

    def __init__(self, domain: str = 'ecommerce'):
        try:
            self.nlp = spacy.load('en_core_web_sm')
        except:
            print("Downloading spaCy model...")
            import os
            os.system('python -m spacy download en_core_web_sm')
            self.nlp = spacy.load('en_core_web_sm')

        self.domain = domain
        self.domain_knowledge = DomainKnowledge()

    def set_domain(self, domain: str):
        """Change the active domain"""
        self.domain = domain

    def get_synonyms(self, word: str) -> Set[str]:
        """Get synonyms using both WordNet AND domain knowledge"""
        synonyms = set()

        # WordNet synonyms
        for syn in wordnet.synsets(word):
            for lemma in syn.lemmas():
                synonyms.add(lemma.name().replace('_', ' '))

        # Domain-specific synonyms (PRIORITY)
        domain_syns = self.domain_knowledge.get_domain_synonyms(self.domain)
        word_normalized = word.lower().replace(' ', '_')

        for syn_group, category in domain_syns.items():
            if word_normalized in syn_group:
                # Add all words from the same group
                synonyms.update([w.replace('_', ' ') for w in syn_group])

        return synonyms

    def are_synonyms(self, word1: str, word2: str, threshold: float = 0.7) -> bool:
        """Check if two words are synonyms (domain-aware)"""
        word1 = word1.lower().strip()
        word2 = word2.lower().strip()

        if word1 == word2:
            return True

        # PRIORITY: Check domain knowledge first
        if self.domain_knowledge.is_domain_synonym(word1, word2, self.domain):
            return True

        # Fallback to WordNet
        syns1 = self.get_synonyms(word1)
        syns2 = self.get_synonyms(word2)

        if word2 in syns1 or word1 in syns2:
            return True

        if syns1 and syns2:
            overlap = len(syns1.intersection(syns2))
            total = len(syns1.union(syns2))
            if total > 0 and (overlap / total) > threshold:
                return True

        return False

    def extract_nouns(self, text: str) -> List[str]:
        """Extract nouns dynamically"""
        doc = self.nlp(text)
        return [token.lemma_ for token in doc if token.pos_ in ['NOUN', 'PROPN']]

    def extract_verbs(self, text: str) -> List[str]:
        """Extract verbs dynamically"""
        doc = self.nlp(text)
        return [token.lemma_ for token in doc if token.pos_ == 'VERB']

    def get_antonyms(self, word: str) -> Set[str]:
        """Get antonyms using both WordNet AND domain knowledge"""
        antonyms = set()

        # WordNet antonyms
        for syn in wordnet.synsets(word):
            for lemma in syn.lemmas():
                if lemma.antonyms():
                    antonyms.add(lemma.antonyms()[0].name())

        # Domain-specific antonyms (PRIORITY)
        domain_ants = self.domain_knowledge.get_domain_antonyms(self.domain)
        word_normalized = word.lower().replace(' ', '_')

        for pair, _ in domain_ants.items():
            if word_normalized in pair[0]:
                antonyms.add(pair[1].replace('_', ' '))
            elif word_normalized in pair[1]:
                antonyms.add(pair[0].replace('_', ' '))

        return antonyms

    def are_antonyms(self, word1: str, word2: str) -> bool:
        """Check if two words are antonyms (domain-aware)"""
        # PRIORITY: Check domain knowledge first
        if self.domain_knowledge.is_domain_antonym(word1, word2, self.domain):
            return True

        # Fallback to WordNet
        antonyms1 = self.get_antonyms(word1)
        antonyms2 = self.get_antonyms(word2)
        return word2 in antonyms1 or word1 in antonyms2

    def extract_semantic_keywords(self, text: str) -> Set[str]:
        """Extract semantically important keywords"""
        doc = self.nlp(text)
        keywords = set()
        for token in doc:
            if token.pos_ in ['NOUN', 'PROPN', 'VERB', 'ADJ'] and not token.is_stop:
                keywords.add(token.lemma_.lower())
        return keywords

# ========== UNIT CONVERSION UTILITY ==========

class DynamicUnitConverter:
    """Dynamic unit conversion using Pint library"""

    def __init__(self):
        self.ureg = UnitRegistry()
        self.debug = False

    def extract_value_unit(self, text: str) -> Optional[Tuple[float, str]]:
        """Extract value and unit from text - IMPROVED"""
        text_lower = text.lower()

        patterns = [
            # Time units
            (r'(\d+\.?\d*)\s*(millisecond|milliseconds|ms)\b', 'millisecond'),
            (r'(\d+\.?\d*)\s*(second|seconds|sec|secs|s)\b', 'second'),
            (r'(\d+\.?\d*)\s*(minute|minutes|min|mins|m)\b', 'minute'),
            (r'(\d+\.?\d*)\s*(hour|hours|hr|hrs|h)\b', 'hour'),
            (r'(\d+\.?\d*)\s*(day|days|d)\b', 'day'),

            # Data units - FIXED: Check MB/GB before just B
            (r'(\d+\.?\d*)\s*(terabyte|terabytes|tb|tbs)\b', 'terabyte'),
            (r'(\d+\.?\d*)\s*(gigabyte|gigabytes|gb|gbs)\b', 'gigabyte'),
            (r'(\d+\.?\d*)\s*(megabyte|megabytes|mb|mbs)\b', 'megabyte'),
            (r'(\d+\.?\d*)\s*(kilobyte|kilobytes|kb|kbs)\b', 'kilobyte'),
            (r'(\d+\.?\d*)\s*(?<!kilo)(?<!mega)(?<!giga)(?<!tera)(byte|bytes|b)\b', 'byte'),

            # Currency
            (r'\$(\d+\.?\d*)', 'USD'),
        ]

        for pattern, standard_unit in patterns:
            match = re.search(pattern, text_lower, re.IGNORECASE)
            if match:
                value = float(match.group(1))
                if self.debug:
                    print(f"  Extracted: {value} {standard_unit} from '{text}'")
                return value, standard_unit

        return None

    def are_equivalent(self, value1: float, unit1: str, value2: float, unit2: str,
                      tolerance: float = 0.001) -> bool:
        """Check if two value-unit pairs are equivalent - FIXED FOR BINARY UNITS"""
        try:
            if self.debug:
                print(f"\n  Comparing: {value1} {unit1} vs {value2} {unit2}")

            # CRITICAL: Handle data units with BINARY conversion (1024-based)
            data_units = ['byte', 'kilobyte', 'megabyte', 'gigabyte', 'terabyte',
                         'kb', 'mb', 'gb', 'tb', 'bytes', 'kilobytes', 'megabytes', 'gigabytes', 'terabytes']
            time_units = ['second', 'minute', 'hour', 'day', 'millisecond',
                         'seconds', 'minutes', 'hours', 'days', 'milliseconds']

            is_data = any(u in unit1.lower() for u in data_units)
            is_time = any(u in unit1.lower() for u in time_units)

            if is_data:
                # MANUAL BINARY CONVERSION (1024-based for computer storage)
                def to_bytes_binary(value, unit):
                    """Convert to bytes using binary (1024) multipliers"""
                    unit_lower = unit.lower()
                    if 'terabyte' in unit_lower or unit_lower == 'tb':
                        return value * 1024 * 1024 * 1024 * 1024
                    elif 'gigabyte' in unit_lower or unit_lower == 'gb':
                        return value * 1024 * 1024 * 1024
                    elif 'megabyte' in unit_lower or unit_lower == 'mb':
                        return value * 1024 * 1024
                    elif 'kilobyte' in unit_lower or unit_lower == 'kb':
                        return value * 1024
                    else:  # bytes
                        return value

                bytes1 = to_bytes_binary(value1, unit1)
                bytes2 = to_bytes_binary(value2, unit2)

                if self.debug:
                    print(f"  Binary conversion (1024-based):")
                    print(f"    {value1} {unit1} = {bytes1} bytes")
                    print(f"    {value2} {unit2} = {bytes2} bytes")

                diff = abs(bytes1 - bytes2)

                if self.debug:
                    print(f"  Difference: {diff} bytes")

                # Allow small tolerance (< 1 byte)
                return diff < 1.0

            elif is_time:
                # Use Pint for time conversions (decimal is fine)
                q1 = self.ureg.Quantity(value1, unit1)
                q2 = self.ureg.Quantity(value2, unit2)

                q1_base = q1.to('second')
                q2_base = q2.to('second')

                if self.debug:
                    print(f"  In seconds: {q1_base} vs {q2_base}")

                diff = abs(q1_base.magnitude - q2_base.magnitude)

                if self.debug:
                    print(f"  Difference: {diff} seconds")

                return diff < 0.01

            else:
                # General comparison using Pint
                q1 = self.ureg.Quantity(value1, unit1)
                q2 = self.ureg.Quantity(value2, unit2)

                q2_converted = q2.to(q1.units)
                diff = abs(q1.magnitude - q2_converted.magnitude)
                relative_diff = diff / max(abs(q1.magnitude), abs(q2_converted.magnitude), 0.0001)

                if self.debug:
                    print(f"  Relative difference: {relative_diff}")

                return relative_diff < tolerance

        except Exception as e:
            if self.debug:
                print(f"  ERROR: {e}")
            return False

    def convert(self, value: float, from_unit: str, to_unit: str) -> Optional[float]:
        """Convert value from one unit to another"""
        try:
            quantity = self.ureg(f"{value} {from_unit}")
            converted = quantity.to(to_unit)
            return converted.magnitude
        except Exception:
            return None

# ========== BASE STRATEGY ==========

class DetectionStrategy:
    def __init__(self, nlp_utils: DomainAwareNLPUtils, unit_converter: DynamicUnitConverter):
        self.nlp_utils = nlp_utils
        self.unit_converter = unit_converter

    def detect(self, req1: str, req2: str, context: dict) -> Tuple[bool, float, dict]:
        raise NotImplementedError

# ========== DUPLICATE STRATEGIES (ENHANCED) ==========

class DuplicateStrategy1_SemanticSimilarity(DetectionStrategy):
    """High cosine similarity"""

    def detect(self, req1, req2, context):
        sim = context['cosine_sim']
        if sim > 0.85:
            return True, sim, {'method': 'high_similarity', 'score': sim}
        return False, 0, {}

class DuplicateStrategy2_NLIEntailment(DetectionStrategy):
    """NLI entailment with moderate similarity"""

    def detect(self, req1, req2, context):
        nli_label = context['nli_label']
        nli_score = context['nli_score']
        sim = context['cosine_sim']

        if nli_label == 'entailment' and nli_score > 0.85 and sim > 0.45:
            confidence = (nli_score + sim) / 2
            return True, confidence, {'method': 'entailment', 'nli_score': nli_score}
        return False, 0, {}

class DuplicateStrategy3_DynamicUnitConversion(DetectionStrategy):
    """Dynamic unit conversion using Pint library - HIGHEST PRIORITY"""

    def detect(self, req1, req2, context):
        result1 = self.unit_converter.extract_value_unit(req1)
        result2 = self.unit_converter.extract_value_unit(req2)

        if not (result1 and result2):
            return False, 0, {}

        value1, unit1 = result1
        value2, unit2 = result2

        # Check if units are equivalent (e.g., 10MB = 10240KB)
        if self.unit_converter.are_equivalent(value1, unit1, value2, unit2):
            converted_value = self.unit_converter.convert(value1, unit1, unit2)
            return True, 0.98, {  # Higher confidence
                'method': 'dynamic_unit_conversion',
                'value1': f"{value1} {unit1}",
                'value2': f"{value2} {unit2}",
                'converted': f"{value1} {unit1} = {converted_value} {unit2}",
                'library': 'pint',
                'equivalent': True
            }

        return False, 0, {}

class DuplicateStrategy4_DomainSynonymDetection(DetectionStrategy):
    """ENHANCED: Domain-aware synonym detection with strict filtering"""

    def detect(self, req1, req2, context):
        nouns1 = set(self.nlp_utils.extract_nouns(req1))
        nouns2 = set(self.nlp_utils.extract_nouns(req2))
        verbs1 = set(self.nlp_utils.extract_verbs(req1))
        verbs2 = set(self.nlp_utils.extract_verbs(req2))

        synonym_matches = []

        # Check noun synonyms
        for noun1 in nouns1:
            for noun2 in nouns2:
                if noun1 == noun2:
                    continue
                if self.nlp_utils.are_synonyms(noun1, noun2):
                    synonym_matches.append(('noun', noun1, noun2))

        # Check verb synonyms
        for verb1 in verbs1:
            for verb2 in verbs2:
                if verb1 == verb2:
                    continue
                if self.nlp_utils.are_synonyms(verb1, verb2):
                    synonym_matches.append(('verb', verb1, verb2))

        if synonym_matches:
            num_matches = len(synonym_matches)
            sim = context['cosine_sim']

            # IMPROVED: More lenient for strong domain matches
            # If we have 2+ synonym matches from domain knowledge, accept with lower similarity
            # If only 1 match, require high similarity
            if num_matches >= 2:
                min_similarity = 0.60  # Lower threshold for multiple matches
            else:
                min_similarity = 0.75  # Higher threshold for single match

            if sim < min_similarity:
                return False, 0, {}

            # Check for conflicting modifiers
            if self.has_conflicting_modifiers(req1, req2):
                return False, 0, {}

            # Check for negation patterns
            if self.has_negation_conflict(req1, req2):
                return False, 0, {}

            confidence = min(0.90, sim + 0.10 + (num_matches * 0.05))
            return True, confidence, {
                'method': 'domain_synonym_match',
                'matches': [f"{m[1]}↔{m[2]}" for m in synonym_matches],
                'count': num_matches,
                'domain': self.nlp_utils.domain
            }

        return False, 0, {}

    def has_conflicting_modifiers(self, req1, req2):
        """Check for conflicting adjectives/determiners"""
        doc1 = self.nlp_utils.nlp(req1)
        doc2 = self.nlp_utils.nlp(req2)

        modifiers1 = [token.text.lower() for token in doc1 if token.pos_ in ['DET', 'ADJ']]
        modifiers2 = [token.text.lower() for token in doc2 if token.pos_ in ['DET', 'ADJ']]

        for mod1 in modifiers1:
            for mod2 in modifiers2:
                if self.nlp_utils.are_antonyms(mod1, mod2):
                    return True
        return False

    def has_negation_conflict(self, req1, req2):
        """Check if one requirement has negation and other doesn't"""
        negation_words = ['not', 'no', 'never', 'cannot', 'must not', 'mustn\'t']

        has_neg1 = any(neg in req1.lower() for neg in negation_words)
        has_neg2 = any(neg in req2.lower() for neg in negation_words)

        # If one has negation and other doesn't, it's likely a conflict
        return has_neg1 != has_neg2

# ========== INCONSISTENCY STRATEGIES (ENHANCED) ==========

class InconsistencyStrategy1_SimilarDifferentValues(DetectionStrategy):
    """High similarity but different numeric values"""

    def extract_numbers(self, req):
        return re.findall(r'\d+\.?\d*', req)

    def detect(self, req1, req2, context):
        nums1 = self.extract_numbers(req1)
        nums2 = self.extract_numbers(req2)

        if not (nums1 and nums2):
            return False, 0, {}

        sim = context['cosine_sim']
        if sim > 0.75 and nums1[0] != nums2[0]:
            # Check if it's unit conversion (should be caught by duplicate strategy)
            result1 = self.unit_converter.extract_value_unit(req1)
            result2 = self.unit_converter.extract_value_unit(req2)

            if result1 and result2:
                value1, unit1 = result1
                value2, unit2 = result2
                if self.unit_converter.are_equivalent(value1, unit1, value2, unit2):
                    return False, 0, {}  # It's a duplicate, not inconsistency

            confidence = sim * 0.9
            return True, confidence, {
                'method': 'similar_different_values',
                'value1': nums1[0],
                'value2': nums2[0]
            }
        return False, 0, {}

class InconsistencyStrategy2_RangeOverlap(DetectionStrategy):
    """Detect overlapping numeric ranges"""

    def extract_range(self, req):
        req_lower = req.lower()

        between_match = re.search(r'between\s+(\d+)\s*(?:and|-)\s*(\d+)', req_lower)
        if between_match:
            return (float(between_match.group(1)), float(between_match.group(2)), 'range')

        min_match = re.search(r'(?:minimum|at least|min)\s+(\d+)', req_lower)
        if min_match:
            return (float(min_match.group(1)), float('inf'), 'minimum')

        max_match = re.search(r'(?:maximum|at most|max|not exceed|less than|limited to)\s+(\d+)', req_lower)
        if max_match:
            return (0, float(max_match.group(1)), 'maximum')

        return None

    def detect(self, req1, req2, context):
        range1 = self.extract_range(req1)
        range2 = self.extract_range(req2)

        if not (range1 and range2):
            return False, 0, {}

        min1, max1, _ = range1
        min2, max2, _ = range2

        overlaps = not (max1 < min2 or max2 < min1)
        identical = (min1 == min2 and max1 == max2)

        if overlaps and not identical and context['cosine_sim'] > 0.5:
            return True, 0.85, {
                'method': 'range_overlap',
                'range1': f"{min1}-{max1}" if max1 != float('inf') else f"min {min1}",
                'range2': f"{min2}-{max2}" if max2 != float('inf') else f"min {min2}",
                'overlap_type': 'partial_overlap'
            }

        return False, 0, {}

class InconsistencyStrategy3_VaguenessDetection(DetectionStrategy):
    """Detect vague vs specific requirements"""

    def detect(self, req1, req2, context):
        req1_lower = req1.lower()
        req2_lower = req2.lower()

        # Don't flag as vague if it's a conflict pattern
        conflict_keywords = ['no ', 'not ', 'never', 'cannot', 'forbidden', 'deny', 'disable']
        has_conflict_1 = any(kw in req1_lower for kw in conflict_keywords)
        has_conflict_2 = any(kw in req2_lower for kw in conflict_keywords)

        if has_conflict_1 or has_conflict_2:
            return False, 0, {}

        doc1 = self.nlp_utils.nlp(req1)
        doc2 = self.nlp_utils.nlp(req2)

        # Vague words
        vague_words = {'fast', 'slow', 'quick', 'efficient', 'good', 'bad', 'large', 'small'}
        has_vague_1 = any(token.text.lower() in vague_words for token in doc1)
        has_vague_2 = any(token.text.lower() in vague_words for token in doc2)

        # Count specific numbers
        numbers_1 = [token for token in doc1 if token.like_num]
        numbers_2 = [token for token in doc2 if token.like_num]

        is_vague_1 = has_vague_1 and len(numbers_1) == 0
        is_vague_2 = has_vague_2 and len(numbers_2) == 0
        is_specific_1 = len(numbers_1) > 0
        is_specific_2 = len(numbers_2) > 0

        if (is_vague_1 and is_specific_2) or (is_vague_2 and is_specific_1):
            if context['cosine_sim'] > 0.5:
                return True, 0.70, {
                    'method': 'vague_vs_specific',
                    'vague_req': req1 if is_vague_1 else req2,
                    'specific_req': req2 if is_vague_1 else req1
                }

        return False, 0, {}

class InconsistencyStrategy4_PartialScopeMismatch(DetectionStrategy):
    """Detect same action with different scopes"""

    def detect(self, req1, req2, context):
        req1_lower = req1.lower()
        req2_lower = req2.lower()

        scope_all = ['all', 'every', 'any', 'entire', 'whole']
        scope_partial = ['their', 'own', 'department', 'team', 'group', 'specific']

        has_all_1 = any(term in req1_lower for term in scope_all)
        has_all_2 = any(term in req2_lower for term in scope_all)
        has_partial_1 = any(term in req1_lower for term in scope_partial)
        has_partial_2 = any(term in req2_lower for term in scope_partial)

        if (has_all_1 and has_partial_2) or (has_partial_1 and has_all_2):
            if context['cosine_sim'] > 0.6:
                return True, 0.75, {
                    'method': 'partial_scope_mismatch',
                    'all_scope': req1 if has_all_1 else req2,
                    'partial_scope': req2 if has_all_1 else req1
                }

        return False, 0, {}

class InconsistencyStrategy5_MathematicalConsistency(DetectionStrategy):
    """Check mathematical relationships"""

    def extract_price_info(self, req):
        req_lower = req.lower()
        price_match = re.search(r'\$(\d+\.?\d*)', req)
        if not price_match:
            return None, None

        price = float(price_match.group(1))

        if 'month' in req_lower or 'monthly' in req_lower:
            period = 'month'
        elif 'year' in req_lower or 'annual' in req_lower or 'yearly' in req_lower:
            period = 'year'
        else:
            period = None

        return price, period

    def detect(self, req1, req2, context):
        price1, period1 = self.extract_price_info(req1)
        price2, period2 = self.extract_price_info(req2)

        if not (price1 and price2 and period1 and period2):
            return False, 0, {}

        if period1 == period2:
            return False, 0, {}

        if period1 == 'month' and period2 == 'year':
            expected_annual = price1 * 12
            if abs(expected_annual - price2) > (expected_annual * 0.15):
                return True, 0.75, {
                    'method': 'mathematical_inconsistency',
                    'monthly': price1,
                    'annual': price2,
                    'expected_annual': expected_annual
                }

        return False, 0, {}

# ========== CONFLICT STRATEGIES (ENHANCED) ==========

class ConflictStrategy1_NLIContradiction(DetectionStrategy):
    """NLI contradiction with semantic relatedness - IMPROVED"""

    def detect(self, req1, req2, context):
        if context['nli_label'] != 'contradiction':
            return False, 0, {}

        nli_score = context['nli_score']
        if nli_score < 0.75:  # Raised threshold
            return False, 0, {}

        sim = context['cosine_sim']
        semantically_related = context['semantically_related']

        # Must be semantically related
        if not semantically_related:
            return False, 0, {}

        # Check if it's actually talking about different things
        keywords1 = self.nlp_utils.extract_semantic_keywords(req1)
        keywords2 = self.nlp_utils.extract_semantic_keywords(req2)

        # Need at least some keyword overlap
        if len(keywords1 & keywords2) == 0 and sim < 0.40:
            return False, 0, {}

        return True, nli_score, {'method': 'nli_contradiction', 'score': nli_score}

class ConflictStrategy2_DomainAntonymDetection(DetectionStrategy):
    """ENHANCED: Domain-aware antonym detection"""

    def detect(self, req1, req2, context):
        verbs1 = set(self.nlp_utils.extract_verbs(req1))
        verbs2 = set(self.nlp_utils.extract_verbs(req2))

        doc1 = self.nlp_utils.nlp(req1)
        doc2 = self.nlp_utils.nlp(req2)

        adjs1 = set([token.lemma_ for token in doc1 if token.pos_ == 'ADJ'])
        adjs2 = set([token.lemma_ for token in doc2 if token.pos_ == 'ADJ'])

        antonym_pairs = []

        # Check verb antonyms
        for verb1 in verbs1:
            for verb2 in verbs2:
                if self.nlp_utils.are_antonyms(verb1, verb2):
                    antonym_pairs.append(('verb', verb1, verb2))

        # Check adjective antonyms
        for adj1 in adjs1:
            for adj2 in adjs2:
                if self.nlp_utils.are_antonyms(adj1, adj2):
                    antonym_pairs.append(('adj', adj1, adj2))

        if antonym_pairs and context['cosine_sim'] > 0.4:
            return True, 0.88, {
                'method': 'domain_antonym_detection',
                'pairs': [f"{p[1]}↔{p[2]}" for p in antonym_pairs],
                'domain': self.nlp_utils.domain
            }

        return False, 0, {}

class ConflictStrategy3_DynamicEntityMismatch(DetectionStrategy):
    """Extract entities dynamically using spaCy"""

    def detect(self, req1, req2, context):
        nouns1 = set(self.nlp_utils.extract_nouns(req1))
        nouns2 = set(self.nlp_utils.extract_nouns(req2))

        actor_nouns = {'user', 'admin', 'customer', 'person', 'system', 'guest', 'employee'}
        primary_nouns1 = nouns1 - actor_nouns
        primary_nouns2 = nouns2 - actor_nouns

        if primary_nouns1 and primary_nouns2:
            if not primary_nouns1.intersection(primary_nouns2):
                are_related = False
                for noun1 in primary_nouns1:
                    for noun2 in primary_nouns2:
                        if self.nlp_utils.are_synonyms(noun1, noun2):
                            are_related = True
                            break
                    if are_related:
                        break

                if not are_related:
                    return True, 0.95, {
                        'method': 'different_primary_entities',
                        'entities1': list(primary_nouns1),
                        'entities2': list(primary_nouns2)
                    }

        return False, 0, {}

class ConflictStrategy4_ImplicitNegation(DetectionStrategy):
    """ENHANCED: Detect implicit contradictions with better context awareness"""

    def detect(self, req1, req2, context):
        req1_lower = req1.lower()
        req2_lower = req2.lower()

        # ENHANCED patterns with better context
        implicit_conflicts = [
            # Connectivity conflicts - but not when describing different scenarios
            (['offline', 'without internet', 'no connection', 'no connectivity', 'disconnected'],
             ['internet required', 'online only', 'connectivity required', 'must be online',
              'requires connection', 'needs internet']),

            # Mandatory vs optional conflicts - only when about same feature
            (['mandatory', 'required', 'must have', 'must be', 'compulsory', 'necessary', 'essential'],
             ['can disable', 'optional', 'can turn off', 'not required', 'not mandatory']),

            # Universal vs exception conflicts
            (['all fields', 'every field', 'always required'],
             ['optional', 'except', 'some fields']),

            # Direct permission conflicts
            (['allow', 'permit', 'enable', 'authorized'],
             ['prohibit', 'block', 'restrict', 'forbidden']),
        ]

        for group1, group2 in implicit_conflicts:
            has_group1 = any(phrase in req1_lower for phrase in group1)
            has_group2 = any(phrase in req2_lower for phrase in group2)

            if has_group1 and has_group2:
                # Higher threshold and check semantic relatedness
                if context['cosine_sim'] > 0.30 and context['semantically_related']:
                    # Additional check: make sure they're talking about similar things
                    keywords1 = self.nlp_utils.extract_semantic_keywords(req1)
                    keywords2 = self.nlp_utils.extract_semantic_keywords(req2)

                    if len(keywords1 & keywords2) > 0:  # At least one common keyword
                        return True, 0.82, {
                            'method': 'implicit_negation',
                            'pattern': f"{group1[0]} vs {group2[0]}"
                        }

        return False, 0, {}

class ConflictStrategy5_ExceptionPattern(DetectionStrategy):
    """ENHANCED: Detect all/mandatory vs optional/exception patterns"""

    def detect(self, req1, req2, context):
        req1_lower = req1.lower()
        req2_lower = req2.lower()

        universal = ['all ', 'every ', 'always', 'mandatory', 'required', 'must', 'entire']
        exception = ['optional', 'except', 'some', 'can be', 'may be', 'not required', 'certain']

        has_universal_1 = any(pattern in req1_lower for pattern in universal)
        has_universal_2 = any(pattern in req2_lower for pattern in universal)
        has_exception_1 = any(pattern in req1_lower for pattern in exception)
        has_exception_2 = any(pattern in req2_lower for pattern in exception)

        if (has_universal_1 and has_exception_2) or (has_exception_1 and has_universal_2):
            if context['cosine_sim'] > 0.30:
                return True, 0.78, {
                    'method': 'exception_pattern',
                    'universal_req': req1 if has_universal_1 else req2,
                    'exception_req': req2 if has_universal_1 else req1
                }

        return False, 0, {}

class ConflictStrategy6_DirectNegation(DetectionStrategy):
    """ENHANCED: Detect direct negation patterns"""

    def detect(self, req1, req2, context):
        req1_lower = req1.lower()
        req2_lower = req2.lower()

        negation_words = ['no ', 'not ', 'never ', 'cannot ', 'forbidden', 'must not']
        permission_words = ['allow', 'permit', 'can ', 'able to', 'enable', 'should']

        has_negation_1 = any(neg in req1_lower for neg in negation_words)
        has_negation_2 = any(neg in req2_lower for neg in negation_words)
        has_permission_1 = any(perm in req1_lower for perm in permission_words)
        has_permission_2 = any(perm in req2_lower for perm in permission_words)

        if (has_negation_1 and has_permission_2) or (has_permission_1 and has_negation_2):
            if context['cosine_sim'] > 0.35:
                return True, 0.86, {
                    'method': 'direct_negation',
                    'negation_req': req1 if has_negation_1 else req2,
                    'permission_req': req2 if has_negation_1 else req1
                }

        return False, 0, {}

# ========== MAIN DETECTOR ==========

class MultiStrategyDetector:
    def __init__(self, domain: str = 'auto'):
        print("Initializing domain-aware NLP utilities...")
        self.domain = domain
        self.nlp_utils = DomainAwareNLPUtils('ecommerce')  # Default

        print("Initializing unit converter (Pint)...")
        self.unit_converter = DynamicUnitConverter()

        # Strategy lists
        self.duplicate_strategies = [
            DuplicateStrategy3_DynamicUnitConversion(self.nlp_utils, self.unit_converter),
            DuplicateStrategy1_SemanticSimilarity(self.nlp_utils, self.unit_converter),
            DuplicateStrategy2_NLIEntailment(self.nlp_utils, self.unit_converter),
            DuplicateStrategy4_DomainSynonymDetection(self.nlp_utils, self.unit_converter),
        ]

        self.inconsistency_strategies = [
            InconsistencyStrategy1_SimilarDifferentValues(self.nlp_utils, self.unit_converter),
            InconsistencyStrategy2_RangeOverlap(self.nlp_utils, self.unit_converter),
            InconsistencyStrategy3_VaguenessDetection(self.nlp_utils, self.unit_converter),
            InconsistencyStrategy4_PartialScopeMismatch(self.nlp_utils, self.unit_converter),
            InconsistencyStrategy5_MathematicalConsistency(self.nlp_utils, self.unit_converter),
        ]

        self.conflict_strategies = [
            ConflictStrategy1_NLIContradiction(self.nlp_utils, self.unit_converter),
            ConflictStrategy2_DomainAntonymDetection(self.nlp_utils, self.unit_converter),
            ConflictStrategy4_ImplicitNegation(self.nlp_utils, self.unit_converter),
            ConflictStrategy5_ExceptionPattern(self.nlp_utils, self.unit_converter),
            ConflictStrategy6_DirectNegation(self.nlp_utils, self.unit_converter),
        ]

        self.conflict_disqualifiers = [
            ConflictStrategy3_DynamicEntityMismatch(self.nlp_utils, self.unit_converter),
        ]

        print("Loading transformer models...")
        self.embedding_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
        self.nli_model = pipeline('text-classification',
                                 model='facebook/bart-large-mnli',
                                 device=-1)
        print("All models loaded!\n")

    def set_domain(self, domain: str):
        """Change the active domain"""
        self.nlp_utils.set_domain(domain)
        print(f"Domain set to: {domain}")

    def analyze_pair(self, req1: str, req2: str, i: int, j: int) -> List[Detection]:
        # ========== PRIORITY 1: UNIT CONVERSION CHECK (BEFORE ANY OTHER ANALYSIS) ==========
        result1 = self.unit_converter.extract_value_unit(req1)
        result2 = self.unit_converter.extract_value_unit(req2)

        if result1 and result2:
            value1, unit1 = result1
            value2, unit2 = result2

            # Debug output
            # print(f"DEBUG: Checking units - {value1}{unit1} vs {value2}{unit2}")

            if self.unit_converter.are_equivalent(value1, unit1, value2, unit2):
                # CONFIRMED DUPLICATE - Return immediately, don't run NLI
                converted_value = self.unit_converter.convert(value1, unit1, unit2)
                # print(f"DEBUG: ✓ Units are equivalent!")
                return [Detection(
                    i, j, req1, req2, IssueType.DUPLICATE, 0.98,
                    {
                        'method': 'dynamic_unit_conversion',
                        'value1': f"{value1} {unit1}",
                        'value2': f"{value2} {unit2}",
                        'converted': f"{value1} {unit1} = {converted_value} {unit2}",
                        'library': 'pint',
                        'equivalent': True
                    }
                )]

        # ========== PRIORITY 2: SEMANTIC ANALYSIS ==========
        embeddings = self.embedding_model.encode([req1, req2])
        cosine_sim = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]

        text = f"{req1} [SEP] {req2}"
        nli_result = self.nli_model(text)[0]

        keywords1 = self.nlp_utils.extract_semantic_keywords(req1)
        keywords2 = self.nlp_utils.extract_semantic_keywords(req2)
        semantically_related = bool(keywords1 & keywords2) or cosine_sim > 0.3

        context = {
            'cosine_sim': cosine_sim,
            'nli_label': nli_result['label'],
            'nli_score': nli_result['score'],
            'semantically_related': semantically_related
        }

        detections = []

        # ========== PRIORITY 2: INCONSISTENCIES ==========
        for strategy in self.inconsistency_strategies:
            detected, confidence, evidence = strategy.detect(req1, req2, context)
            if detected and confidence >= 0.70:
                detections.append(Detection(
                    i, j, req1, req2, IssueType.INCONSISTENCY, confidence, evidence
                ))
                return detections

        # ========== PRIORITY 3: CONFLICTS (High Priority) ==========
        conflict_disqualified = False
        for disqualifier in self.conflict_disqualifiers:
            disqualified, _, _ = disqualifier.detect(req1, req2, context)
            if disqualified:
                conflict_disqualified = True
                break

        if not conflict_disqualified:
            for strategy in self.conflict_strategies:
                detected, confidence, evidence = strategy.detect(req1, req2, context)
                if detected and confidence >= 0.70:
                    detections.append(Detection(
                        i, j, req1, req2, IssueType.CONFLICT, confidence, evidence
                    ))
                    return detections

        # ========== PRIORITY 4: OTHER DUPLICATE STRATEGIES ==========
        for strategy in self.duplicate_strategies:
            if isinstance(strategy, DuplicateStrategy3_DynamicUnitConversion):
                continue  # Already handled above
            detected, confidence, evidence = strategy.detect(req1, req2, context)
            if detected and confidence >= 0.70:
                detections.append(Detection(
                    i, j, req1, req2, IssueType.DUPLICATE, confidence, evidence
                ))
                return detections

        return detections

    def analyze_requirements(self, requirements: List[str], verbose=True, auto_detect_domain=True):
        # Auto-detect domain if requested
        if auto_detect_domain and self.domain == 'auto':
            detected_domain = DomainKnowledge.detect_domain(requirements)
            self.set_domain(detected_domain)
            print(f"📍 Auto-detected domain: {detected_domain.upper()}\n")

        all_detections = []

        if verbose:
            print("=" * 80)
            print("ANALYZING REQUIREMENTS")
            print("=" * 80)

        for i in range(len(requirements)):
            for j in range(i + 1, len(requirements)):
                detections = self.analyze_pair(requirements[i], requirements[j], i, j)

                if verbose and detections:
                    print(f"\n🔍 Req {i} vs Req {j}")
                    print(f"   Req {i}: {requirements[i]}")
                    print(f"   Req {j}: {requirements[j]}")
                    for detection in detections:
                        symbol = {"duplicate": "✓", "conflict": "✗", "inconsistency": "⚠"}[detection.issue_type.value]
                        print(f"   {symbol} {detection.issue_type.value.upper()} (confidence: {detection.confidence:.2f})")
                        print(f"      Evidence: {detection.evidence}")

                all_detections.extend(detections)

        return all_detections

    def print_summary(self, detections: List[Detection]):
        duplicates = [d for d in detections if d.issue_type == IssueType.DUPLICATE]
        conflicts = [d for d in detections if d.issue_type == IssueType.CONFLICT]
        inconsistencies = [d for d in detections if d.issue_type == IssueType.INCONSISTENCY]

        print("\n" + "=" * 80)
        print("SUMMARY")
        print("=" * 80)
        print(f"\n✓ DUPLICATES: {len(duplicates)}")
        for d in duplicates:
            print(f"   Req {d.req1_id} ↔ Req {d.req2_id} (confidence: {d.confidence:.2f})")

        print(f"\n✗ CONFLICTS: {len(conflicts)}")
        for d in conflicts:
            print(f"   Req {d.req1_id} ↔ Req {d.req2_id} (confidence: {d.confidence:.2f})")

        print(f"\n⚠ INCONSISTENCIES: {len(inconsistencies)}")
        for d in inconsistencies:
            print(f"   Req {d.req1_id} ↔ Req {d.req2_id} (confidence: {d.confidence:.2f})")

        print(f"\n📊 Total Issues: {len(detections)}")

# ========== USAGE ==========
if __name__ == "__main__":
    # Initialize with auto domain detection
    detector = MultiStrategyDetector(domain='auto')

    print("\n" + "🔥 " * 40)
    print("TEST 1: E-COMMERCE REQUIREMENTS")
    print("🔥 " * 40)

    ecommerce_requirements = [
        "Users must be able to add items to their shopping cart",
        "The system shall allow customers to place products in their basket",
        "Payment must be processed within 5 seconds",
        "Session timeout is 30 minutes",
        "User sessions expire after 1800 seconds",
        "Maximum file upload size is 10 megabytes",
        "File size limit is 10240 kilobytes",
        "Response time must be under 2000 milliseconds",
        "API calls should complete within 2 seconds",
        "Customers can save items to their wishlist",
        "Users can bookmark products for later",
    ]

    detections = detector.analyze_requirements(ecommerce_requirements)
    detector.print_summary(detections)

    print("\n\n" + "🔥 " * 40)
    print("TEST 2: EDGE CASES & CONFLICTS")
    print("🔥 " * 40)

    edge_case_requirements = [
        "The system must support both online and offline modes",
        "Internet connectivity is required at all times",
        "User password must be between 8-16 characters",
        "Password length should be minimum 12 characters",
        "Admin can view all user profiles",
        "Admin can view user profiles in their department",
        "Users must not upload files larger than 10MB",
        "File uploads are limited to 5MB",
        "Session timeout is 30 minutes",
        "User sessions expire after 1800 seconds",
        "Refunds are allowed within 14 days",
        "No refunds for digital products",
        "Two-factor authentication is mandatory",
        "Users can disable security features in settings",
        "Response time should be fast",
        "API calls must complete within 200ms",
        "Premium subscription costs $50 per month",
        "Annual premium plan is $500",
        "All fields are mandatory",
        "Phone number is optional for international users",
    ]

    detections2 = detector.analyze_requirements(edge_case_requirements)
    detector.print_summary(detections2)

    print("\n\n" + "🔥 " * 40)
    print("TEST 3: HEALTHCARE DOMAIN")
    print("🔥 " * 40)

    # Manually set domain for testing
    detector.set_domain('healthcare')

    healthcare_requirements = [
        "Doctor must prescribe medication for the patient",
        "Physician should order drugs for the individual",
        "Patient records must be kept confidential",
        "Medical files should be publicly accessible",
        "Appointments can be scheduled online",
        "Consultations can be booked via internet",
        "Prescription must be approved by physician",
        "Medication order requires doctor authorization",
    ]

    detections3 = detector.analyze_requirements(healthcare_requirements, auto_detect_domain=False)
    detector.print_summary(detections3)

    print("\n\n" + "🔥 " * 40)
    print("TEST 4: BANKING DOMAIN")
    print("🔥 " * 40)

    detector.set_domain('banking')

    banking_requirements = [
        "Users can deposit money into their account",
        "Customers can credit funds to their profile",
        "Withdrawal limit is $500 per day",
        "Users can take out $1000 daily",
        "Account balance must be positive",
        "Funds cannot go into negative",
        "Transfer money between accounts",
        "Send funds to another profile",
        "ATM withdrawals are allowed",
        "Cash machine access is prohibited",
    ]

    detections4 = detector.analyze_requirements(banking_requirements, auto_detect_domain=False)
    detector.print_summary(detections4)

    print("\n\n" + "🔥 " * 40)
    print("TEST 5: UNIT CONVERSION VERIFICATION")
    print("🔥 " * 40)

    detector.set_domain('ecommerce')

    unit_test_requirements = [
        "Maximum file upload size is 10 megabytes",
        "File size limit is 10240 kilobytes",
        "Session timeout is 30 minutes",
        "User sessions expire after 1800 seconds",
        "Response time must be under 2000 milliseconds",
        "API calls should complete within 2 seconds",
    ]

    print("\n🔬 DEBUGGING UNIT CONVERSION:")
    print("=" * 80)

    # Manual test
    converter = DynamicUnitConverter()
    converter.debug = True

    print("\nTest 1: 10 megabytes vs 10240 kilobytes")
    r1 = converter.extract_value_unit("Maximum file upload size is 10 megabytes")
    r2 = converter.extract_value_unit("File size limit is 10240 kilobytes")
    print(f"  Result 1: {r1}")
    print(f"  Result 2: {r2}")
    if r1 and r2:
        print(f"\n  Mathematical check:")
        print(f"    10 MB = 10 * 1024 KB = {10 * 1024} KB")
        print(f"    Expected: 10240 KB")
        print(f"    Match: {10 * 1024 == 10240}")

        equiv = converter.are_equivalent(r1[0], r1[1], r2[0], r2[1])
        print(f"\n  Pint equivalence check: {equiv}")
    print()

    converter.debug = False

    detections5 = detector.analyze_requirements(unit_test_requirements, auto_detect_domain=False)
    detector.print_summary(detections5)

edge_case_requirements = [
    # GROUP 1: IMPLICIT vs EXPLICIT CONFLICTS
    "The system must support both online and offline modes",
    "Internet connectivity is required at all times",

    # GROUP 2: OVERLAPPING RANGES (Tricky!)
    "User password must be between 8-16 characters",
    "Password length should be minimum 12 characters",

    # GROUP 3: PARTIAL DUPLICATES (Same action, different scope)
    "Admin can view all user profiles",
    "Admin can view user profiles in their department",

    # GROUP 4: NEGATION AMBIGUITY
    "Users must not upload files larger than 10MB",
    "File uploads are limited to 5MB",

    # GROUP 5: TIME CONFLICTS (Different units)
    "Session timeout is 30 minutes",
    "User sessions expire after 1800 seconds",

    # GROUP 6: PERMISSION HIERARCHY (Not actually conflicts)
    "Regular users can read documents",
    "Admin users can read and edit documents",

    # GROUP 7: CONDITIONAL vs ABSOLUTE
    "Refunds are allowed within 14 days",
    "No refunds for digital products",

    # GROUP 8: IMPLICIT REQUIREMENTS (Hidden dependencies)
    "Two-factor authentication is mandatory",
    "Users can disable security features in settings",

    # GROUP 9: VAGUE vs SPECIFIC (Precision mismatch)
    "Response time should be fast",
    "API calls must complete within 200ms",

    # GROUP 10: MULTIPLE ACTORS (Who does what)
    "System administrators can delete user accounts",
    "Users can delete their own accounts",

    # GROUP 11: CURRENCY/UNIT CONFUSION
    "Premium subscription costs $50 per month",
    "Annual premium plan is $500",

    # GROUP 12: LANGUAGE AMBIGUITY
    "Data must be backed up regularly",
    "Daily backups are required at midnight",

    # GROUP 13: TEMPORAL CONFLICTS (Before/After)
    "Notifications must be sent before order shipment",
    "Shipping confirmation is sent after payment processing",

    # GROUP 14: EXCEPTION HANDLING
    "All fields are mandatory",
    "Phone number is optional for international users",

    # GROUP 15: SCOPE CREEP
    "The app must work on iOS devices",
    "Support for Android, iOS, and web browsers is required",
]

requirements = [
        "Users must be able to add items to their shopping cart",
        "The system shall allow customers to place products in their basket",
        "Payment must be processed within 5 seconds",
        "Session timeout is 30 minutes",
        "User sessions expire after 1800 seconds",
        "Maximum file upload size is 10 megabytes",
        "File size limit is 10240 kilobytes",
        "Response time must be under 2000 milliseconds",
        "API calls should complete within 2 seconds",
    ]