"""
=============================================================================
Reqify - FR/NFR Classifier Test Suite  (Direct Model — No API)
=============================================================================
Loads RobertaForSequenceClassification directly from:
    modules/BasicClassifier/

Run from the python_ai_engine directory:
    pytest test/test_fr_nfr_classifier.py -v

Or from the test/ directory:
    cd test
    pytest test_fr_nfr_classifier.py -v
=============================================================================
"""

import os
import sys
import torch
import pytest
from transformers import RobertaTokenizer, RobertaForSequenceClassification

# ---------------------------------------------------------------------------
# Ensure the python_ai_engine directory is on sys.path so relative model
# paths resolve correctly (works whether pytest is run from python_ai_engine
# or from the test/ sub-directory).
# ---------------------------------------------------------------------------
THIS_DIR = os.path.dirname(os.path.abspath(__file__))          # .../test/
ENGINE_DIR = os.path.abspath(os.path.join(THIS_DIR, ".."))     # .../python_ai_engine/
if ENGINE_DIR not in sys.path:
    sys.path.insert(0, ENGINE_DIR)

MODEL_DIR = os.path.join(ENGINE_DIR, "modules", "BasicClassifier")

# ---------------------------------------------------------------------------
# Session-scoped fixture  –  model is loaded ONCE for the whole test session
# ---------------------------------------------------------------------------
@pytest.fixture(scope="session")
def classifier():
    """Load the FR/NFR RoBERTa model and tokenizer from disk (once per run)."""
    print(f"\n[fixture] Loading tokenizer from: {MODEL_DIR}")
    tokenizer = RobertaTokenizer.from_pretrained(MODEL_DIR)

    print(f"[fixture] Loading model from: {MODEL_DIR}")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = RobertaForSequenceClassification.from_pretrained(MODEL_DIR)
    model.to(device)
    model.eval()

    labels = {0: "FR", 1: "NFR"}
    print(f"[fixture] Model ready on {device}. Labels: {labels}\n")

    return tokenizer, model, labels, device


# ---------------------------------------------------------------------------
# Helper used by every test
# ---------------------------------------------------------------------------
def predict(text: str, tokenizer, model, labels, device) -> str:
    """Run inference and return 'FR' or 'NFR'."""
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits

    probs = torch.softmax(logits, dim=1)
    pred_index = torch.argmax(probs, dim=1).item()
    return labels[pred_index]


# ---------------------------------------------------------------------------
# Test data  – (tc_id, description, requirement_text, expected_prediction)
# ---------------------------------------------------------------------------
TEST_CASES = [
    # ── E-Commerce Domain ─────────────────────────────────────────────────
    ("TC001", "Verify FR classification of REQ-1",
     "The system shall allow registered users to browse product catalog by category.",
     "FR"),
    ("TC002", "Verify FR classification of REQ-2",
     "The system shall allow registered users to add products to shopping cart with quantity selection.",
     "FR"),
    ("TC003", "Verify FR classification of REQ-3",
     "The system shall allow registered users to remove items from shopping cart at any time.",
     "FR"),
    ("TC004", "Verify FR classification of REQ-4",
     "The system shall allow registered users to place orders using saved payment methods with order confirmation.",
     "FR"),
    ("TC005", "Verify FR classification of REQ-5",
     "The system shall allow registered users to track order status in real time after purchase.",
     "FR"),
    ("TC006", "Verify FR classification of REQ-6",
     "The system shall allow registered users to submit product reviews after order delivery.",
     "FR"),
    ("TC007", "Verify FR classification of REQ-7",
     "The system shall allow registered users to add products to wishlist for later purchase.",
     "FR"),
    ("TC008", "Verify FR classification of REQ-8",
     "The system shall allow registered users to apply discount coupons during checkout with validity check.",
     "FR"),
    ("TC009", "Verify FR classification of REQ-9",
     "The system shall allow admin users to manage product inventory by updating stock levels.",
     "FR"),
    ("TC010", "Verify FR classification of REQ-10",
     "The system shall allow admin users to process refund requests within 3 business days.",
     "FR"),
    ("TC011", "Verify FR classification of REQ-11",
     "The system shall allow registered users to search products by keyword with filter support.",
     "FR"),
    ("TC012", "Verify FR classification of REQ-12",
     "The system shall allow registered users to view order history from their account dashboard.",
     "FR"),
    ("TC013", "Verify FR classification of REQ-13",
     "The system shall allow admin users to generate sales reports by date range.",
     "FR"),
    ("TC014", "Verify FR classification of REQ-14",
     "The system shall allow registered users to manage their shipping addresses in account settings.",
     "FR"),
    ("TC015", "Verify FR classification of REQ-15",
     "The system shall allow registered users to complete payment using credit card, debit card, or digital wallet.",
     "FR"),
    ("TC016", "Verify NFR classification of REQ-16",
     "The system shall respond to product search queries within 2 seconds under normal load.",
     "NFR"),
    ("TC017", "Verify NFR classification of REQ-17",
     "The system shall support at least 500 concurrent users without performance degradation.",
     "NFR"),
    ("TC018", "Verify NFR classification of REQ-18",
     "The system shall encrypt all payment and personal data using AES-256 encryption.",
     "NFR"),
    ("TC019", "Verify FR classification of REQ-19",
     "The system shall authenticate all users using JWT tokens with 24-hour expiration.",
     "FR"),
    ("TC020", "Verify NFR classification of REQ-20",
     "The system shall be available 99.9% of the time on a monthly basis.",
     "NFR"),
    ("TC021", "Verify NFR classification of REQ-21",
     "The system shall recover from any server failure within 5 minutes without data loss.",
     "NFR"),
    ("TC022", "Verify NFR classification of REQ-22",
     "The system shall provide a responsive web interface accessible on desktop and mobile browsers.",
     "NFR"),
    ("TC023", "Verify NFR classification of REQ-23",
     "The system shall allow new users to complete their first purchase within 10 minutes without external help.",
     "NFR"),
    ("TC024", "Verify NFR classification of REQ-24",
     "The system shall run on Chrome, Firefox, Safari, and Edge browsers without functional differences.",
     "NFR"),
    ("TC025", "Verify NFR classification of REQ-25",
     "The system shall integrate with third-party payment gateways including Stripe and PayPal.",
     "NFR"),
    ("TC026", "Verify NFR classification of REQ-26",
     "The system shall be deployable on AWS, Azure, and Google Cloud without code changes.",
     "NFR"),
    ("TC027", "Verify NFR classification of REQ-27",
     "The system shall follow modular architecture to allow addition of new modules without affecting existing ones.",
     "NFR"),
    ("TC028", "Verify NFR classification of REQ-28",
     "The system shall log all user actions including login, purchase, and profile updates for audit purposes.",
     "NFR"),
    ("TC029", "Verify FR classification of REQ-29",
     "The system shall process orders quickly and efficiently.",
     "FR"),
    ("TC030", "Verify NFR classification of REQ-30",
     "The system should handle many users simultaneously without issues.",
     "NFR"),
    ("TC031", "Verify NFR classification of REQ-31",
     "The system shall provide a user-friendly and intuitive shopping experience.",
     "NFR"),
    ("TC032", "Verify NFR classification of REQ-32",
     "The system shall ensure products are delivered in a reasonable time.",
     "NFR"),
    ("TC033", "Verify NFR classification of REQ-33",
     "The system shall bank all transaction data securely in the backend.",
     "NFR"),
    ("TC034", "Verify FR classification of REQ-34",
     "The system shall allow users register using email and password.",
     "FR"),
    ("TC035", "Verify NFR classification of REQ-35",
     "The system should support registration by using email and password.",
     "NFR"),
    ("TC036", "Verify FR classification of REQ-36",
     "The registered user shall be able to view past orders from their profile page.",
     "FR"),
    ("TC037", "Verify FR classification of REQ-37",
     "The system shall allow guest users to checkout without creating an account.",
     "FR"),
    ("TC038", "Verify NFR classification of REQ-38",
     "The system shall require all users to register and log in before accessing checkout.",
     "NFR"),
    ("TC039", "Verify FR classification of REQ-39",
     "The system shall process all refund requests within 24 hours of submission.",
     "FR"),
    ("TC040", "Verify NFR classification of REQ-40",
     "The system shall process refund requests within 7 to 10 business days after approval.",
     "NFR"),
    ("TC041", "Verify NFR classification of REQ-41",
     "The system shall support a maximum of 200 concurrent users at peak load.",
     "NFR"),
    ("TC042", "Verify FR classification of REQ-42",
     "The system shall display product prices in USD only across all pages.",
     "FR"),
    ("TC043", "Verify FR classification of REQ-43",
     "The system shall allow users to view product prices in their local currency based on location.",
     "FR"),
    # ── Food Delivery Domain ───────────────────────────────────────────────
    ("TC044", "Verify FR classification of REQ-44",
     "The system shall allow registered users to browse nearby restaurants by location and cuisine type.",
     "FR"),
    ("TC045", "Verify FR classification of REQ-45",
     "The system shall allow registered users to view restaurant menus with item descriptions and prices.",
     "FR"),
    ("TC046", "Verify FR classification of REQ-46",
     "The system shall allow registered users to add food items to cart with quantity and customization options.",
     "FR"),
    ("TC047", "Verify FR classification of REQ-47",
     "The system shall allow registered users to remove items from cart before checkout.",
     "FR"),
    ("TC048", "Verify FR classification of REQ-48",
     "The system shall allow registered users to place food orders using saved payment methods with order confirmation.",
     "FR"),
    ("TC049", "Verify FR classification of REQ-49",
     "The system shall allow registered users to track delivery status in real time after order placement.",
     "FR"),
    ("TC050", "Verify FR classification of REQ-50",
     "The system shall allow registered users to rate and review restaurants after order delivery.",
     "FR"),
    ("TC051", "Verify FR classification of REQ-51",
     "The system shall allow registered users to apply promo codes during checkout with validity check.",
     "FR"),
    ("TC052", "Verify FR classification of REQ-52",
     "The system shall allow registered users to schedule orders for a future delivery time with confirmation.",
     "FR"),
    ("TC053", "Verify FR classification of REQ-53",
     "The system shall allow registered users to view order history from their account dashboard.",
     "FR"),
    ("TC054", "Verify FR classification of REQ-54",
     "The system shall allow registered users to manage saved delivery addresses in account settings.",
     "FR"),
    ("TC055", "Verify FR classification of REQ-55",
     "The system shall allow registered users to reorder from previous orders with a single action.",
     "FR"),
    ("TC056", "Verify FR classification of REQ-56",
     "The system shall allow restaurant owners to manage their menu by adding, updating, or removing items.",
     "FR"),
    ("TC057", "Verify FR classification of REQ-57",
     "The system shall allow restaurant owners to accept or reject incoming orders within 2 minutes.",
     "FR"),
    ("TC058", "Verify FR classification of REQ-58",
     "The system shall allow delivery agents to update delivery status at each checkpoint in real time.",
     "FR"),
    ("TC059", "Verify FR classification of REQ-59",
     "The system shall allow admin users to manage restaurant listings and verify partner restaurants.",
     "FR"),
    ("TC060", "Verify FR classification of REQ-60",
     "The system shall allow registered users to complete payment using credit card, debit card, cash on delivery, or digital wallet.",
     "FR"),
    ("TC061", "Verify FR classification of REQ-61",
     "The system shall allow registered users to contact customer support through in-app chat after order placement.",
     "FR"),
    ("TC062", "Verify NFR classification of REQ-62",
     "The system shall load restaurant listings within 3 seconds under normal network conditions.",
     "NFR"),
    ("TC063", "Verify NFR classification of REQ-63",
     "The system shall support at least 1000 concurrent users without performance degradation.",
     "NFR"),
    ("TC064", "Verify NFR classification of REQ-64",
     "The system shall encrypt all payment and personal data using AES-256 encryption.",
     "NFR"),
    ("TC065", "Verify FR classification of REQ-65",
     "The system shall authenticate all users using JWT tokens with 24-hour expiration.",
     "FR"),
    ("TC066", "Verify NFR classification of REQ-66",
     "The system shall log all user actions including login, order placement, and payment for audit purposes.",
     "NFR"),
    ("TC067", "Verify NFR classification of REQ-67",
     "The system shall be available 99.9% of the time on a monthly basis.",
     "NFR"),
    ("TC068", "Verify NFR classification of REQ-68",
     "The system shall recover from any server failure within 5 minutes without data loss.",
     "NFR"),
    ("TC069", "Verify NFR classification of REQ-69",
     "The system shall provide a responsive mobile-first interface accessible on Android and iOS.",
     "NFR"),
    ("TC070", "Verify NFR classification of REQ-70",
     "The system shall allow new users to place their first order within 5 minutes without external help.",
     "NFR"),
    ("TC071", "Verify NFR classification of REQ-71",
     "The system shall run on Chrome, Firefox, Safari, and Edge browsers without functional differences.",
     "NFR"),
    ("TC072", "Verify FR classification of REQ-72",
     "The system shall integrate with third-party mapping services including Google Maps for delivery tracking.",
     "FR"),
    ("TC073", "Verify NFR classification of REQ-73",
     "The system shall be deployable on AWS, Azure, and Google Cloud without code changes.",
     "NFR"),
    ("TC074", "Verify NFR classification of REQ-74",
     "The system shall follow modular architecture to allow addition of new features without affecting existing modules.",
     "NFR"),
    ("TC075", "Verify NFR classification of REQ-75",
     "The system shall provide API documentation for all endpoints to support future integrations.",
     "NFR"),
    ("TC076", "Verify FR classification of REQ-76",
     "The system shall deliver food orders as fast as possible to nearby customers.",
     "FR"),
    ("TC077", "Verify NFR classification of REQ-77",
     "The system should handle a large number of simultaneous orders without slowing down.",
     "NFR"),
    ("TC078", "Verify NFR classification of REQ-78",
     "The system shall provide a smooth and pleasant ordering experience for all users.",
     "NFR"),
    ("TC079", "Verify NFR classification of REQ-79",
     "The system shall ensure delivery agents reach customers in a reasonable amount of time.",
     "NFR"),
    ("TC080", "Verify NFR classification of REQ-80",
     "The system shall process payments in a secure and efficient manner at all times.",
     "NFR"),
    ("TC081", "Verify FR classification of REQ-81",
     "The system shall allow customers to add meals to their basket before placing an order.",
     "FR"),
    ("TC082", "Verify FR classification of REQ-82",
     "The system shall allow users to put food items into cart prior to checkout.",
     "FR"),
    ("TC083", "Verify FR classification of REQ-83",
     "The system shall allow registered users to view their past food orders from their profile.",
     "FR"),
    ("TC084", "Verify FR classification of REQ-84",
     "The system shall allow users to access previous order history from the account section.",
     "FR"),
    ("TC085", "Verify FR classification of REQ-85",
     "The system shall allow guest users to place food orders without creating an account.",
     "FR"),
    ("TC086", "Verify FR classification of REQ-86",
     "The system shall require all users to register and log in before accessing the ordering feature.",
     "FR"),
    ("TC087", "Verify FR classification of REQ-87",
     "The system shall automatically assign the nearest available delivery agent to every new order.",
     "FR"),
    ("TC088", "Verify FR classification of REQ-88",
     "The system shall allow restaurant owners to choose and assign their own preferred delivery agents.",
     "FR"),
    ("TC089", "Verify NFR classification of REQ-89",
     "The system shall support a maximum of 300 concurrent users at peak load.",
     "NFR"),
    ("TC090", "Verify FR classification of REQ-90",
     "The system shall display all menu prices in USD only across all restaurant pages.",
     "FR"),
    ("TC091", "Verify FR classification of REQ-91",
     "The system shall display menu prices in the local currency of the user based on their detected location.",
     "FR"),
    ("TC092", "Verify FR classification of REQ-92",
     "The system shall cancel unaccepted orders automatically after 5 minutes of no restaurant response.",
     "FR"),
    ("TC093", "Verify FR classification of REQ-93",
     "The system shall wait up to 15 minutes before cancelling orders that have not been accepted by the restaurant.",
     "FR"),
    # ── E-Learning Domain ──────────────────────────────────────────────────
    ("TC094", "Verify FR classification of REQ-94",
     "The system shall allow admin users to create and manage courses with title, description, and category.",
     "FR"),
    ("TC095", "Verify FR classification of REQ-95",
     "The system shall allow instructors to upload course content including videos, PDFs, and presentations.",
     "FR"),
    ("TC096", "Verify FR classification of REQ-96",
     "The system shall allow registered students to browse and search available courses by category and keyword.",
     "FR"),
    ("TC097", "Verify FR classification of REQ-97",
     "The system shall allow registered students to enroll in courses after completing payment or free registration.",
     "FR"),
    ("TC098", "Verify FR classification of REQ-98",
     "The system shall allow registered students to access course content after successful enrollment.",
     "FR"),
    ("TC099", "Verify FR classification of REQ-99",
     "The system shall allow registered students to track their course progress with completion percentage.",
     "FR"),
    ("TC100", "Verify FR classification of REQ-100",
     "The system shall allow instructors to create quizzes and assignments with configurable deadlines.",
     "FR"),
    ("TC101", "Verify FR classification of REQ-101",
     "The system shall allow registered students to attempt quizzes within the allowed time limit and submission window.",
     "FR"),
    ("TC102", "Verify FR classification of REQ-102",
     "The system shall allow instructors to grade student assignments and provide written feedback.",
     "FR"),
    ("TC103", "Verify FR classification of REQ-103",
     "The system shall allow registered students to view their grades and feedback from the course dashboard.",
     "FR"),
    ("TC104", "Verify FR classification of REQ-104",
     "The system shall allow registered students to participate in course discussion forums by posting and replying.",
     "FR"),
    ("TC105", "Verify FR classification of REQ-105",
     "The system shall allow instructors to schedule and host live classes with registered enrolled students.",
     "FR"),
    ("TC106", "Verify FR classification of REQ-106",
     "The system shall allow registered students to download course completion certificates after finishing all requirements.",
     "FR"),
    ("TC107", "Verify FR classification of REQ-107",
     "The system shall allow admin users to manage user accounts including students and instructors.",
     "FR"),
    ("TC108", "Verify FR classification of REQ-108",
     "The system shall allow registered students to submit assignments before the deadline with file upload support.",
     "FR"),
    ("TC109", "Verify FR classification of REQ-109",
     "The system shall allow instructors to send announcements to all enrolled students of a course.",
     "FR"),
    ("TC110", "Verify FR classification of REQ-110",
     "The system shall allow registered students to save courses to a wishlist for later enrollment.",
     "FR"),
    ("TC111", "Verify FR classification of REQ-111",
     "The system shall allow admin users to generate reports on course enrollment and student performance.",
     "FR"),
    ("TC112", "Verify NFR classification of REQ-112",
     "The system shall load course content pages within 3 seconds under normal network conditions.",
     "NFR"),
    ("TC113", "Verify NFR classification of REQ-113",
     "The system shall support at least 2000 concurrent users without performance degradation.",
     "NFR"),
    ("TC114", "Verify NFR classification of REQ-114",
     "The system shall encrypt all user data and payment information using AES-256 encryption.",
     "NFR"),
    ("TC115", "Verify FR classification of REQ-115",
     "The system shall authenticate all users using JWT tokens with 24-hour expiration.",
     "FR"),
    ("TC116", "Verify NFR classification of REQ-116",
     "The system shall log all user actions including login, enrollment, and submission for audit purposes.",
     "NFR"),
    ("TC117", "Verify NFR classification of REQ-117",
     "The system shall be available 99.9% of the time on a monthly basis.",
     "NFR"),
    ("TC118", "Verify NFR classification of REQ-118",
     "The system shall recover from any server failure within 5 minutes without loss of student progress data.",
     "NFR"),
    ("TC119", "Verify NFR classification of REQ-119",
     "The system shall provide a responsive interface accessible on desktop, tablet, and mobile browsers.",
     "NFR"),
    ("TC120", "Verify NFR classification of REQ-120",
     "The system shall allow new students to enroll in their first course within 5 minutes without external help.",
     "NFR"),
    ("TC121", "Verify NFR classification of REQ-121",
     "The system shall run on Chrome, Firefox, Safari, and Edge browsers without functional differences.",
     "NFR"),
    ("TC122", "Verify NFR classification of REQ-122",
     "The system shall integrate with third-party video streaming services including YouTube and Vimeo.",
     "NFR"),
    ("TC123", "Verify NFR classification of REQ-123",
     "The system shall be deployable on AWS, Azure, and Google Cloud without code changes.",
     "NFR"),
    ("TC124", "Verify NFR classification of REQ-124",
     "The system shall follow modular architecture to allow addition of new modules without affecting existing features.",
     "NFR"),
    ("TC125", "Verify NFR classification of REQ-125",
     "The system shall provide API documentation for all endpoints to support future third-party integrations.",
     "NFR"),
    ("TC126", "Verify NFR classification of REQ-126",
     "The system shall deliver course content quickly and smoothly to all students.",
     "NFR"),
    ("TC127", "Verify NFR classification of REQ-127",
     "The system should handle a large number of students accessing courses at the same time without issues.",
     "NFR"),
    ("TC128", "Verify NFR classification of REQ-128",
     "The system shall provide an engaging and interactive learning experience for all users.",
     "NFR"),
    ("TC129", "Verify FR classification of REQ-129",
     "The system shall ensure instructors can easily manage their course materials without difficulty.",
     "FR"),
    ("TC130", "Verify FR classification of REQ-130",
     "The system shall process student payments in a secure and timely manner during enrollment.",
     "FR"),
    ("TC131", "Verify FR classification of REQ-131",
     "The system shall allow learners to sign up for available courses after making payment.",
     "FR"),
    ("TC132", "Verify FR classification of REQ-132",
     "The system shall allow students to register for a course upon successful fee submission.",
     "FR"),
    ("TC133", "Verify FR classification of REQ-133",
     "The system shall allow registered students to view their assessment scores from the learning portal.",
     "FR"),
    ("TC134", "Verify FR classification of REQ-134",
     "The system shall allow students to access their quiz and assignment results from the course page.",
     "FR"),
    ("TC135", "Verify FR classification of REQ-135",
     "The system shall allow guest users to access and view full course content without registration.",
     "FR"),
    ("TC136", "Verify NFR classification of REQ-136",
     "The system shall require all users to register and log in before accessing any course content.",
     "NFR"),
    ("TC137", "Verify FR classification of REQ-137",
     "The system shall automatically pass all students who complete 100 percent of course videos.",
     "FR"),
    ("TC138", "Verify FR classification of REQ-138",
     "The system shall require students to pass all quizzes and assignments before receiving course completion certification.",
     "FR"),
    ("TC139", "Verify NFR classification of REQ-139",
     "The system shall support a maximum of 500 concurrent users at peak load.",
     "NFR"),
    ("TC140", "Verify FR classification of REQ-140",
     "The system shall display all course prices in USD only across all pages.",
     "FR"),
    ("TC141", "Verify FR classification of REQ-141",
     "The system shall display course prices in the local currency of the student based on their detected location.",
     "FR"),
    ("TC142", "Verify FR classification of REQ-142",
     "The system shall automatically issue course completion certificates immediately after the final quiz submission.",
     "FR"),
    ("TC143", "Verify FR classification of REQ-143",
     "The system shall issue course completion certificates only after instructor manual approval of all submitted assignments.",
     "FR"),
]


# ---------------------------------------------------------------------------
# Parametrised test function
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    "tc_id, description, requirement_text, expected_prediction",
    TEST_CASES,
    ids=[tc[0] for tc in TEST_CASES],
)
def test_fr_nfr_classification(
    classifier, tc_id, description, requirement_text, expected_prediction
):
    """
    Directly calls the loaded RoBERTa model (no API).
    Asserts that the model prediction matches the expected FR/NFR label.
    """
    tokenizer, model, labels, device = classifier
    actual = predict(requirement_text, tokenizer, model, labels, device)

    assert actual == expected_prediction, (
        f"\n[{tc_id}] {description}\n"
        f"  Requirement : {requirement_text}\n"
        f"  Expected    : {expected_prediction}\n"
        f"  Got         : {actual}"
    )
